---
- name: Playbook to configure ansible controller post installation
  hosts: all
  connection: local
  roles:
    - {role: infra.aap_configuration.settings, when: controller_settings is defined}
...