---
- name: Playbook to configure ansible controller post installation
  hosts: all
  connection: local
  collections: infra.aap_configuration
  roles:
    - {role: infra.aap_configuration.dispatch, when: controller_settings is defined}
...